/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
//   tutorialSidebar: [
//     { type: "doc", id: "intro" },
//     {
//       type: 'category',
//       label: 'Docusaurus',
//       link: {
//         type: 'generated-index',
//         title: 'Docusaurus Guides',
//         description:
//           "Let's learn about the most important Docusaurus concepts!",
//         keywords: ['guides'],
//         image: '/img/docusaurus.png',
//       },
//       items: [
//         {
//           type: 'doc',
//           id: 'Algorithms🧮/bit',
//         },
        
//       ],
//     },
//     {
//       type: 'link',
//       label: 'Learn more',
//       href: 'https://example.com',
//     },
//   ],
  
};

module.exports = sidebars;
